window.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id), container=$('game-container');
 if(!window.THREE){$('message').textContent='Não foi possível carregar o motor 3D. Verifique sua conexão.';return}
 const scene=new THREE.Scene(); scene.background=new THREE.Color(0x06101f); scene.fog=new THREE.Fog(0x06101f,42,78);
 const lowPower=matchMedia('(pointer:coarse)').matches||navigator.hardwareConcurrency<=4||innerWidth<700;
 const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,150), renderer=new THREE.WebGLRenderer({antialias:!lowPower,powerPreference:'high-performance'});
 renderer.setPixelRatio(lowPower?1:Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=!lowPower;renderer.outputColorSpace=THREE.SRGBColorSpace;container.appendChild(renderer.domElement);
 let audioContext=null,soundOn=localStorage.getItem('be-game-sound')!=='off';
 async function unlockAudio(){if(!soundOn)return;try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')await audioContext.resume();tone(520,.05,'sine',0,.001)}catch(error){soundOn=false;updateSoundButton()}}
 let progress={bestScore:0,bestLevel:1,character:0,playerName:'Atleta BE',ranking:[],achievements:[]};try{progress={...progress,...JSON.parse(localStorage.getItem('be-game-progress')||'{}')}}catch(error){}
 let deviceId=localStorage.getItem('be-game-device-id');if(!deviceId){deviceId=crypto.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(16).slice(2)}`;localStorage.setItem('be-game-device-id',deviceId)}let globalRanking=[];
 const achievementData={firstWater:{icon:'💧',name:'Primeira hidratação'},score500:{icon:'⭐',name:'Craque dos 500'},shieldSave:{icon:'🛡',name:'Defesa perfeita'},level2:{icon:'🚩',name:'Novo desafio'}};
 function renderAchievements(){const earned=new Set(progress.achievements||[]),list=$('achievement-list');list.replaceChildren();Object.entries(achievementData).forEach(([id,item])=>{const el=document.createElement('div');el.className=`achievement-item ${earned.has(id)?'unlocked':''}`;el.textContent=`${earned.has(id)?item.icon:'🔒'} ${item.name}`;list.append(el)});$('achievement-count').textContent=`${earned.size}/${Object.keys(achievementData).length}`}
 let toastTimer;function unlockAchievement(id){if(!achievementData[id]||(progress.achievements||[]).includes(id))return;progress.achievements=[...(progress.achievements||[]),id];localStorage.setItem('be-game-progress',JSON.stringify(progress));renderAchievements();const toast=$('achievement-toast');toast.textContent=`🎖 Conquista: ${achievementData[id].name}`;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800);sounds.win()}
 function renderProgress(){$('best-score').textContent=progress.bestScore;$('best-level').textContent=progress.bestLevel;const list=$('ranking-list'),entries=globalRanking.length?globalRanking:(progress.ranking||[]);list.replaceChildren();entries.slice(0,10).forEach((entry,index)=>{const li=document.createElement('li'),score=document.createElement('strong');li.append(document.createTextNode(`${index+1}. ${entry.name||'Atleta BE'}`));score.textContent=entry.score;li.append(score);list.append(li)});if(!list.children.length){const li=document.createElement('li');li.textContent='Seja o primeiro a entrar no ranking.';list.append(li)}renderAchievements()}
 async function loadGlobalRanking(){try{const response=await fetch('/api/game-ranking',{cache:'no-store'});if(!response.ok)throw new Error('ranking');const data=await response.json();globalRanking=Array.isArray(data.ranking)?data.ranking:[];$('ranking-status').textContent='online';renderProgress()}catch(error){$('ranking-status').textContent='modo local';renderProgress()}}
 async function startRankedRun(){state.runToken=null;try{const response=await fetch('/api/game-ranking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start',deviceId})});if(!response.ok)throw new Error('inicio');const data=await response.json();state.runToken=data.runToken||null}catch(error){$('ranking-status').textContent='partida local'}}
 async function submitGlobalScore(){if(!state.runToken)return;try{const response=await fetch('/api/game-ranking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:(progress.playerName||'Atleta BE').trim()||'Atleta BE',score:state.score,level:state.level,character:progress.character,deviceId,runToken:state.runToken})});if(!response.ok)throw new Error('envio');const data=await response.json();globalRanking=Array.isArray(data.ranking)?data.ranking:globalRanking;$('ranking-status').textContent=data.position?`posição ${data.position}`:'online';renderProgress()}catch(error){$('ranking-status').textContent='envio pendente'}}
 function saveProgress(){progress.bestScore=Math.max(progress.bestScore,state?.score||0);progress.bestLevel=Math.max(progress.bestLevel,state?.level||1);localStorage.setItem('be-game-progress',JSON.stringify(progress));renderProgress()}
 function recordScore(){const score=state?.score||0;if(score>0){const name=(progress.playerName||'Atleta BE').trim()||'Atleta BE';progress.ranking=[...(progress.ranking||[]).filter(item=>!(item.name===name&&item.score===score)),{name,score,level:state.level}].sort((a,b)=>b.score-a.score).slice(0,5);submitGlobalScore()}saveProgress()}
 $('player-name').value=progress.playerName;$('player-name').addEventListener('input',event=>{progress.playerName=event.target.value.slice(0,16);localStorage.setItem('be-game-progress',JSON.stringify(progress))});$('player-name').addEventListener('pointerdown',event=>event.stopPropagation());
 function tone(frequency,duration=.12,type='sine',delay=0,volume=.055){if(!soundOn)return;try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();const start=audioContext.currentTime+delay,osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(start);osc.stop(start+duration)}catch(error){soundOn=false}}
 const sounds={water:()=>{tone(620,.1);tone(880,.14,'sine',.07)},bar:()=>{tone(330,.09,'square');tone(495,.12,'square',.06)},shield:()=>{tone(440,.18);tone(660,.22,'sine',.1);tone(990,.25,'sine',.2)},turbo:()=>{tone(220,.12,'sawtooth');tone(440,.16,'sawtooth',.08);tone(880,.2,'sawtooth',.16)},caught:()=>{tone(260,.22,'sawtooth');tone(160,.35,'sawtooth',.16)},win:()=>{[523,659,784,1047].forEach((f,i)=>tone(f,.28,'sine',i*.12,.07))}};
 function updateSoundButton(){$('sound-toggle').textContent=soundOn?'🔊':'🔇';$('sound-toggle').setAttribute('aria-label',soundOn?'Desativar sons':'Ativar sons')}
 $('sound-toggle').addEventListener('click',()=>{soundOn=!soundOn;localStorage.setItem('be-game-sound',soundOn?'on':'off');updateSoundButton();if(soundOn)tone(660,.12)});updateSoundButton();
 scene.add(new THREE.HemisphereLight(0x9ddcff,0x06101f,1.25));const sun=new THREE.DirectionalLight(0xffffff,1.4);sun.position.set(-18,35,16);sun.castShadow=!lowPower;scene.add(sun);
 const baseMaze=[[1,1,1,1,1,1,1,1,1,1,1,1,1],[1,0,0,0,1,0,0,0,1,0,0,0,1],[1,0,1,0,1,0,1,0,1,0,1,0,1],[1,0,1,0,0,0,1,0,0,0,1,0,1],[1,0,1,1,1,0,1,1,1,0,1,0,1],[1,0,0,0,0,0,0,0,1,0,0,0,1],[1,1,1,0,1,1,1,0,1,1,1,0,1],[1,0,0,0,1,0,0,0,0,0,0,0,1],[1,0,1,1,1,0,1,1,1,0,1,0,1],[1,0,0,0,0,0,0,0,1,0,0,0,1],[1,1,1,1,1,1,1,1,1,1,1,1,1]];function mazeForLevel(level){const original=baseMaze.map(row=>[...row]);if(level===2)return original.map(row=>[...row].reverse());if(level===3)return [...original].reverse().map(row=>[...row].reverse());return original}let maze=mazeForLevel(1);const CELL=4,rows=maze.length,cols=maze[0].length,ox=-(cols-1)*CELL/2,oz=-(rows-1)*CELL/2;
 const world=(x,y)=>new THREE.Vector3(ox+x*CELL,0,oz+y*CELL),open=(x,y)=>maze[y]?.[x]===0;
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(cols*CELL+12,rows*CELL+12),new THREE.MeshStandardMaterial({color:0x0b2335,roughness:.82}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 const grid=new THREE.GridHelper(cols*CELL+12,cols+3,0x167c73,0x104055);grid.position.y=.02;scene.add(grid);
 const wallGeo=new THREE.BoxGeometry(CELL*.94,2.8,CELL*.94),wallMat=new THREE.MeshStandardMaterial({color:0x126390,roughness:.35,metalness:.25}),capMat=new THREE.MeshBasicMaterial({color:0x21b9b1}),wallGroup=new THREE.Group();scene.add(wallGroup);
 function buildMaze(level=1){wallGroup.clear();const colors=[[0x126390,0x21b9b1],[0x6738a3,0xc359ff],[0x9b4b19,0xffa735],[0x176b50,0x35ed9e]],palette=colors[(level-1)%colors.length];wallMat.color.setHex(palette[0]);capMat.color.setHex(palette[1]);maze.forEach((row,y)=>row.forEach((v,x)=>{if(v){const m=new THREE.Mesh(wallGeo,wallMat);m.position.copy(world(x,y));m.position.y=1.4;m.castShadow=!lowPower;m.receiveShadow=true;wallGroup.add(m);const cap=new THREE.Mesh(new THREE.BoxGeometry(CELL*.82,.12,CELL*.82),capMat);cap.position.set(m.position.x,2.86,m.position.z);wallGroup.add(cap)}}))}buildMaze();
 function athlete(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.SphereGeometry(.82,24,18),new THREE.MeshStandardMaterial({color,roughness:.35}));body.scale.set(1,1.1,1);body.castShadow=true;g.add(body);const visor=new THREE.Mesh(new THREE.BoxGeometry(1.05,.28,.35),new THREE.MeshStandardMaterial({color:0x07111f,metalness:.7}));visor.position.set(0,.2,.72);g.add(visor);[-.48,.48].forEach(x=>{const shoe=new THREE.Mesh(new THREE.BoxGeometry(.38,.25,.68),new THREE.MeshStandardMaterial({color:0xffffff}));shoe.position.set(x,-.77,.18);g.add(shoe)});g.position.y=1;scene.add(g);return g}
 const enemy=athlete(0x20242b);enemy.scale.set(1.12,1.12,1.12);const refereeShirt=new THREE.Mesh(new THREE.BoxGeometry(1.35,1.05,.72),new THREE.MeshStandardMaterial({color:0xffd21f,roughness:.7}));refereeShirt.position.set(0,-.05,.05);enemy.add(refereeShirt);const refereeStripe=new THREE.Mesh(new THREE.BoxGeometry(.14,1.08,.75),new THREE.MeshStandardMaterial({color:0x111111}));refereeStripe.position.set(0,-.05,.08);enemy.add(refereeStripe);const whistle=new THREE.Mesh(new THREE.TorusGeometry(.13,.045,8,18),new THREE.MeshStandardMaterial({color:0xf1f3f5,metalness:.8}));whistle.position.set(.35,.18,.55);enemy.add(whistle);let player=new THREE.Group();scene.add(player);
 const characterNames=['Futebol','Basquete','Vôlei','Tênis','Beisebol','Futebol Americano'];let characterCanvas=null;
 function removeMagenta(img){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const p=ctx.getImageData(0,0,c.width,c.height),d=p.data;for(let i=0;i<d.length;i+=4){const power=d[i]+d[i+2]-d[i+1]*1.45;if(d[i]>170&&d[i+2]>150&&power>160){d[i+3]=255-Math.max(0,Math.min(255,(power-160)*3));d[i]=Math.min(d[i],d[i+1]);d[i+2]=Math.min(d[i+2],d[i+1])}}ctx.putImageData(p,0,0);return c}
 function characterTexture(index){const col=index%3,row=Math.floor(index/3),cell=document.createElement('canvas');cell.width=characterCanvas.width/3;cell.height=characterCanvas.height/2;cell.getContext('2d').drawImage(characterCanvas,col*cell.width,row*cell.height,cell.width,cell.height,0,0,cell.width,cell.height);return cell}
 function selectCharacter(index){progress.character=index;localStorage.setItem('be-game-progress',JSON.stringify(progress));document.querySelectorAll('#characters button').forEach((b,i)=>b.classList.toggle('selected',i===index));$('character-name').textContent=characterNames[index];player.clear();const texture=new THREE.CanvasTexture(characterTexture(index));texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,alphaTest:.08}));sprite.scale.set(4.4,4.4,1);sprite.position.y=1.25;player.add(sprite)}
 function loadCharacters(){const img=new Image();img.src='img/personagens-3d-chroma.png';img.onload=()=>{requestAnimationFrame(()=>{characterCanvas=removeMagenta(img);const holder=$('characters');characterNames.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.title=name;b.setAttribute('aria-label',name);b.appendChild(characterTexture(i));b.onclick=()=>selectCharacter(i);holder.appendChild(b)});selectCharacter(Math.max(0,Math.min(5,progress.character||0)))})};img.onerror=()=>{$('character-name').textContent='Personagem padrão'}}renderProgress();loadGlobalRanking();loadCharacters();
 const itemGroup=new THREE.Group();scene.add(itemGroup);let itemCells=[];
 function itemSprite(symbol){const canvas=document.createElement('canvas');canvas.width=canvas.height=192;const ctx=canvas.getContext('2d');ctx.font='132px "Segoe UI Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbol,96,102);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,alphaTest:.03}));sprite.scale.set(1.9,1.9,1);return sprite}
 function powerLabel(title,description,color){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='rgba(4,18,35,.88)';ctx.strokeStyle=color;ctx.lineWidth=4;ctx.roundRect(8,8,496,112,30);ctx.fill();ctx.stroke();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 38px Inter,Arial,sans-serif';ctx.fillStyle='#fff';ctx.fillText(title,256,48);ctx.font='700 25px Inter,Arial,sans-serif';ctx.fillStyle=color;ctx.fillText(description,256,87);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false}));sprite.scale.set(3.6,.9,1);sprite.position.y=1.75;return sprite}
 function makeItem(type,x,y){const g=new THREE.Group();if(type==='water'){const plastic=new THREE.MeshPhysicalMaterial({color:0x9be9ff,transparent:true,opacity:.78,roughness:.12,metalness:0,transmission:.12});const body=new THREE.Mesh(new THREE.CylinderGeometry(.32,.38,1.05,20),plastic);body.position.y=-.05;g.add(body);const shoulder=new THREE.Mesh(new THREE.CylinderGeometry(.20,.32,.25,20),plastic);shoulder.position.y=.58;g.add(shoulder);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.22,16),plastic);neck.position.y=.80;g.add(neck);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.205,.205,.16,16),new THREE.MeshStandardMaterial({color:0x176bd6,roughness:.45}));cap.position.y=.98;g.add(cap);const label=new THREE.Mesh(new THREE.CylinderGeometry(.325,.365,.34,20),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.55}));label.position.y=-.03;g.add(label);const stripe=new THREE.Mesh(new THREE.CylinderGeometry(.332,.372,.13,20),new THREE.MeshStandardMaterial({color:0x14bfe8}));stripe.position.y=-.03;g.add(stripe);g.scale.set(.9,.9,.9)}else if(type==='bar')g.add(itemSprite('🍫'));else if(type==='fruit')g.add(itemSprite('🍎'));else if(type==='sleep')g.add(itemSprite('😴'));else if(type==='shield'){const shield=new THREE.Mesh(new THREE.IcosahedronGeometry(.62,1),new THREE.MeshStandardMaterial({color:0x49ddff,emissive:0x087eaa,transparent:true,opacity:.88,metalness:.35}));g.add(shield);const ring=new THREE.Mesh(new THREE.TorusGeometry(.82,.07,10,28),new THREE.MeshBasicMaterial({color:0xb7f5ff}));ring.rotation.x=Math.PI/2;g.add(ring);g.add(powerLabel('ESCUDO','10s de proteção','#61eaff'))}else{const bolt=new THREE.Mesh(new THREE.ConeGeometry(.58,1.25,5),new THREE.MeshStandardMaterial({color:0xffd33d,emissive:0xff7300}));bolt.rotation.z=-.45;g.add(bolt);const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.06,8,24),new THREE.MeshBasicMaterial({color:0xffe999}));ring.rotation.x=Math.PI/2;g.add(ring);g.add(powerLabel('VELOCIDADE','8s mais rápido','#ffca45'))}g.position.copy(world(x,y));g.position.y=.95;g.userData={type,x,y,value:type==='water'?15:['bar','fruit','sleep'].includes(type)?25:0};itemGroup.add(g)}
 const LEVEL_TIME=120,formatTime=seconds=>`${String(Math.floor(Math.max(0,seconds)/60)).padStart(2,'0')}:${String(Math.ceil(Math.max(0,seconds)%60)).padStart(2,'0')}`;
 const state={score:0,level:1,lives:3,collected:0,water:0,bars:0,total:0,playing:false,paused:false,capturing:false,runToken:null,needsBar:false,requiredRecovery:null,milestone:0,phaseStartScore:0,phaseStartWater:0,player:{x:1,y:1},target:{x:1,y:1},enemy:{x:11,y:9},enemyTarget:{x:11,y:9},queued:null,heading:null,accelerating:false,speed:8.2,shield:0,turbo:0,enemyTimer:0,invincible:0,timeRemaining:LEVEL_TIME};
 setInterval(()=>{$('danger-warning').classList.toggle('visible',state.playing&&!state.paused&&state.invincible<=0&&player.position.distanceTo(enemy.position)<9)},150);
 function reachableCorridors(){const queue=[{x:1,y:1}],seen=new Set(['1,1']);while(queue.length){const cell=queue.shift();Object.values(dirs).forEach(direction=>{const x=cell.x+direction.x,y=cell.y+direction.y,key=`${x},${y}`;if(open(x,y)&&!seen.has(key)){seen.add(key);queue.push({x,y})}})}return seen}
 function populate(){itemGroup.clear();itemCells=[];const candidates=[],reachable=reachableCorridors();maze.forEach((row,y)=>row.forEach((v,x)=>{if(!v&&reachable.has(`${x},${y}`)&&!(x===1&&y===1)&&!(x===11&&y===9)){if((x+y)%2===1)itemCells.push({x,y,type:'water'});else if(!(x===11&&y===1)&&!(x===1&&y===9))candidates.push({x,y})}}));const recoveryTypes=['bar','fruit','sleep'],phasePositions=[[.18,.5,.82],[.68,.26,.9],[.42,.78,.1]][(state.level-1)%3];phasePositions.forEach((position,index)=>{const cell=candidates[Math.min(candidates.length-1,Math.floor(candidates.length*position))];if(cell)itemCells.push({...cell,type:recoveryTypes[index]})});itemCells.forEach(i=>makeItem(i.type,i.x,i.y));if(reachable.has('11,1'))makeItem('shield',11,1);if(reachable.has('1,9'))makeItem('turbo',1,9);state.total=itemCells.length;state.collected=0}
 function place(){player.position.copy(world(state.player.x,state.player.y));player.position.y=1;enemy.position.copy(world(state.enemy.x,state.enemy.y));enemy.position.y=1}
 function ui(msg){$('score').textContent=state.score;$('level').textContent=state.level;$('lives').textContent='♥ '.repeat(state.lives).trim()||'—';$('timer').textContent=formatTime(state.timeRemaining);$('items').textContent=`${state.collected}/${state.total}`;$('water-count').textContent=state.water;$('bar-count').textContent=`${state.bars}/3`;const recoveryLabels={bar:'▰ Barrinha obrigatória',fruit:'🍎 Fruta obrigatória',sleep:'😴 Descanso obrigatório'};$('power-status').innerHTML=`${state.needsBar?`<span class="turbo">${recoveryLabels[state.requiredRecovery]}</span>`:''}${state.shield>0?`<span class="shield">🛡 Escudo · proteção ${Math.ceil(state.shield)}s</span>`:''}${state.turbo>0?`<span class="turbo">⚡ Velocidade +120% · ${Math.ceil(state.turbo)}s</span>`:''}`;if(state.water>=1)unlockAchievement('firstWater');if(state.score>=500)unlockAchievement('score500');if(state.level>=2)unlockAchievement('level2');if(msg){$('message').textContent=msg;if(msg.startsWith('+15'))sounds.water();else if(msg.startsWith('+25'))sounds.bar();else if(msg.includes('Escudo ativado'))sounds.shield();else if(msg.includes('Turbo ativado'))sounds.turbo()}}
 function reset(all=true){if(all){state.score=0;state.level=1;state.lives=3;state.water=0;state.phaseStartScore=0;state.phaseStartWater=0}state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.accelerating=false;state.capturing=false;state.speed=8.2;state.shield=0;state.turbo=0;state.bars=0;state.needsBar=false;state.requiredRecovery=null;state.milestone=0;state.timeRemaining=LEVEL_TIME;state.invincible=2;populate();place();ui('3 vidas e 2 minutos: complete a fase antes do tempo acabar!')}
 const dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
 function queue(d){state.queued=d;if(state.playing&&!state.paused)tryMove()}
 function tryMove(){if(player.position.distanceTo(world(state.target.x,state.target.y).setY(1))>.16)return;state.player={...state.target};let d=state.queued;if(d&&open(state.player.x+d.x,state.player.y+d.y)){state.heading=d}else{d=state.heading}if(d&&open(state.player.x+d.x,state.player.y+d.y))state.target={x:state.player.x+d.x,y:state.player.y+d.y};else state.heading=null}
 function nextEnemy(){const start=state.enemy,goal=state.player,q=[start],seen=new Set([`${start.x},${start.y}`]),prev=new Map();let found=null;while(q.length){const c=q.shift();if(c.x===goal.x&&c.y===goal.y){found=c;break}Object.values(dirs).forEach(d=>{const n={x:c.x+d.x,y:c.y+d.y},k=`${n.x},${n.y}`;if(open(n.x,n.y)&&!seen.has(k)){seen.add(k);prev.set(k,c);q.push(n)}})}if(!found)return;let step=found,parent=prev.get(`${step.x},${step.y}`);while(parent&&!(parent.x===start.x&&parent.y===start.y)){step=parent;parent=prev.get(`${step.x},${step.y}`)}state.enemyTarget={...step}}
 const hydrationMessages=[['Parabéns, você se hidratou!','Dez garrafinhas concluídas. Seu corpo agradece e sua energia continua lá em cima!'],['Hidratação em dia!','Você chegou a vinte garrafinhas. Excelente ritmo para seguir no desafio!'],['Atleta bem hidratado!','Trinta garrafinhas coletadas. Você mostrou equilíbrio, foco e cuidado com a saúde!']];
 const recoveryRules=[{type:'bar',label:'uma barrinha de cereal 🍫',icon:'🍫',name:'Barrinha de cereal'},{type:'fruit',label:'uma fruta 🍎',icon:'🍎',name:'Fruta nutritiva'},{type:'sleep',label:'o ícone de descanso 😴',icon:'😴',name:'Pausa para descansar'}];
 function hydrationBreak(){state.needsBar=true;state.requiredRecovery=recoveryRules[state.milestone%3].type;state.milestone++;state.playing=false;state.accelerating=false;const message=hydrationMessages[(state.milestone-1)%hydrationMessages.length],rule=recoveryRules[state.milestone-1],preview=$('recovery-preview');$('hydration-title').textContent=message[0];$('hydration-text').textContent=message[1];preview.textContent=rule.icon;preview.className=`recovery-preview ${rule.type}`;preview.setAttribute('aria-label',rule.name);$('recovery-item-name').textContent=rule.name;$('recovery-challenge').textContent=`Agora encontre e recolha ${rule.label}`;$('hydration-popup').classList.add('visible');sounds.win();ui(`Pausa de recuperação: encontre ${rule.label} para liberar as garrafas.`)}
 function collectItem(item){const type=item.userData.type,recoveryTypes=['bar','fruit','sleep'];if(type==='water'&&state.needsBar){ui('Complete a pausa de recuperação antes de pegar mais água!');return}if(recoveryTypes.includes(type)&&(!state.needsBar||type!==state.requiredRecovery)){const labels={bar:'barrinha',fruit:'fruta',sleep:'descanso'};ui(state.needsBar?`Agora você precisa do item correto: não é ${labels[type]}.`:`Guarde o item ${labels[type]} para a pausa certa.`);return}itemGroup.remove(item);if(type==='shield'){state.shield=10;ui('Escudo ativado por 10 segundos!');return}if(type==='turbo'){state.turbo=8;ui('Turbo ativado por 8 segundos!');return}state.score+=item.userData.value;state.collected++;if(recoveryTypes.includes(type)){state.bars++;state.needsBar=false;state.requiredRecovery=null;const names={bar:'Barrinha',fruit:'Fruta',sleep:'Descanso'};ui(`+25 pontos · ${names[type]} concluído. Garrafas liberadas!`)}else{state.water++;ui(`+15 pontos · Garrafa ${state.water}`);if(state.water%10===0&&state.bars<3)hydrationBreak()}if(state.collected>=state.total)complete()}
 $('hydration-continue').addEventListener('click',()=>{$('hydration-popup').classList.remove('visible');state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};enemy.position.copy(world(11,9).setY(1));state.playing=true;state.invincible=2.5;const rule=recoveryRules[state.milestone-1];ui(`Encontre ${rule.label} para liberar as garrafas!`)});
 function loseLife(reason,captured=false){if(state.capturing)return;state.capturing=true;state.playing=false;state.paused=false;state.accelerating=false;state.lives=Math.max(0,state.lives-1);if(captured){sounds.caught();document.body.classList.add('captured')}ui(`${reason} ${state.lives?`Você tem ${state.lives} vida${state.lives>1?'s':''} restante${state.lives>1?'s':''}.`:'Suas 3 vidas acabaram.'}`);setTimeout(()=>{document.body.classList.remove('captured');state.capturing=false;if(state.lives>0){state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.shield=0;state.turbo=0;state.timeRemaining=LEVEL_TIME;state.invincible=2.5;place();state.playing=true;ui(`${reason} Recomece a fase com ${state.lives} vida${state.lives>1?'s':''} e 2 minutos no relógio.`);return}const finalScore=state.score;recordScore();reset(true);$('overlay').classList.add('visible');document.querySelector('.card h1').innerHTML='Fim de<br><em>partida</em>';document.querySelector('.card>p:not(.eyebrow)').textContent=`Você marcou ${finalScore} pontos e perdeu as 3 vidas. Escolha seu atleta para tentar novamente.`;$('start').textContent='Tentar novamente';$('pause').textContent='Ⅱ'},captured?760:350)}
 function hit(){if(state.invincible>0||state.capturing)return;if(state.shield>0){sounds.shield();unlockAchievement('shieldSave');state.shield=0;state.invincible=2.5;enemy.position.copy(world(11,9).setY(1));state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};ui('O escudo bloqueou o vilão!');return}loseLife('O marcador alcançou você.',true)}
 function timeUp(){if(state.capturing)return;state.playing=false;state.paused=false;state.accelerating=false;state.score=state.phaseStartScore;state.water=state.phaseStartWater;state.lives=3;state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.speed=8.2;state.shield=0;state.turbo=0;state.bars=0;state.needsBar=false;state.requiredRecovery=null;state.milestone=0;state.timeRemaining=LEVEL_TIME;populate();place();state.invincible=2;$('ready-level').textContent=state.level;$('phase-ready').classList.add('visible');ui(`O tempo acabou. A fase ${state.level} foi reiniciada e todos os itens voltaram ao circuito.`)}
 function renderFinalRanking(){const entries=[...(globalRanking.length?globalRanking:(progress.ranking||[]))].sort((a,b)=>b.score-a.score).slice(0,10),list=$('final-ranking-list');list.replaceChildren(...entries.map((entry,index)=>{const li=document.createElement('li');li.textContent=`${index+1}. ${entry.name||'Atleta BE'} — ${entry.score} pontos`;return li}));if(!entries.length){const li=document.createElement('li');li.textContent=`1. ${(progress.playerName||'Atleta BE')} — ${state.score} pontos`;list.append(li)}}
 function finishGame(){state.playing=false;recordScore();$('final-player').textContent=(progress.playerName||'Atleta').trim()||'Atleta';$('final-score').textContent=state.score;$('final-water').textContent=state.water;renderFinalRanking();$('game-finished').classList.add('visible');loadGlobalRanking().then(renderFinalRanking)}
 function complete(){state.playing=false;state.accelerating=false;state.score+=100;recordScore();sounds.win();ui('Missão concluída! Bônus de 100 pontos.');if(state.level>=3){finishGame();return}$('result-level').textContent=state.level;$('result-score').textContent=state.score;$('result-water').textContent=state.water;$('result-time').textContent=formatTime(state.timeRemaining);$('mission-complete').classList.add('visible')}
 function nextLevel(){state.level++;saveProgress();state.phaseStartScore=state.score;state.phaseStartWater=state.water;maze=mazeForLevel(state.level);buildMaze(state.level);state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.speed=8.2;state.shield=0;state.turbo=0;state.bars=0;state.needsBar=false;state.requiredRecovery=null;state.milestone=0;state.timeRemaining=LEVEL_TIME;populate();place();state.invincible=1.5;state.playing=false;state.paused=false;$('ready-level').textContent=state.level;$('mission-complete').classList.remove('visible');$('phase-ready').classList.add('visible');ui(`Fase ${state.level} pronta. Novo caminho, mesma tela: toque em iniciar para liberar o relógio.`)}
 const clock=new THREE.Clock();let powerUiTimer=0;function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),t=performance.now()/1000,target=world(state.target.x,state.target.y).setY(1);if(state.playing&&!state.paused){state.timeRemaining=Math.max(0,state.timeRemaining-dt);if(state.timeRemaining<=0){timeUp()}else{state.invincible=Math.max(0,state.invincible-dt);state.shield=Math.max(0,state.shield-dt);state.turbo=Math.max(0,state.turbo-dt);powerUiTimer+=dt;if(powerUiTimer>.25){powerUiTimer=0;ui()}const desiredSpeed=state.turbo>0?18:state.accelerating?14.5:8.2;state.speed+=Math.sign(desiredSpeed-state.speed)*Math.min(Math.abs(desiredSpeed-state.speed),dt*(state.accelerating||state.turbo>0?4.2:9));const step=state.speed*dt,distance=player.position.distanceTo(target);if(distance>step)player.position.add(target.clone().sub(player.position).normalize().multiplyScalar(step));else{player.position.copy(target);tryMove()}state.enemyTimer+=dt;if(enemy.position.distanceTo(world(state.enemyTarget.x,state.enemyTarget.y).setY(1))<.12){state.enemy={...state.enemyTarget};if(state.enemyTimer>.38-Math.min(.15,state.level*.018)){state.enemyTimer=0;nextEnemy()}}const enemyGoal=world(state.enemyTarget.x,state.enemyTarget.y).setY(1);enemy.position.lerp(enemyGoal,Math.min(1,dt*(3+state.level*.13)));itemGroup.children.slice().forEach(i=>{i.rotation.y+=dt*1.7;i.position.y=.95+Math.sin(t*3+i.userData.x)*.12;if(player.position.distanceTo(i.position)<1.2)collectItem(i)});const sameCell=state.player.x===state.enemy.x&&state.player.y===state.enemy.y,crossing=state.player.x===state.enemyTarget.x&&state.player.y===state.enemyTarget.y&&state.target.x===state.enemy.x&&state.target.y===state.enemy.y;if(player.position.distanceTo(enemy.position)<2.05||sameCell||crossing)hit()}}camera.position.lerp(new THREE.Vector3(player.position.x,30,player.position.z+27),.06);camera.lookAt(player.position.x,0,player.position.z-2);renderer.render(scene,camera)}
 const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'},heldKeys=new Set();addEventListener('keydown',e=>{if(keyMap[e.key]){e.preventDefault();heldKeys.add(e.key);state.accelerating=true;queue(dirs[keyMap[e.key]])}if(e.code==='Space'){e.preventDefault();togglePause()}});addEventListener('keyup',e=>{if(keyMap[e.key]){heldKeys.delete(e.key);state.accelerating=heldKeys.size>0}});addEventListener('blur',()=>{heldKeys.clear();state.accelerating=false});const controlArea=document.querySelector('.controls');controlArea.addEventListener('contextmenu',e=>e.preventDefault());controlArea.addEventListener('selectstart',e=>e.preventDefault());document.querySelectorAll('[data-dir]').forEach(b=>{const go=e=>{e.preventDefault();b.classList.add('pressed');state.accelerating=true;queue(dirs[b.dataset.dir]);if(b.setPointerCapture)b.setPointerCapture(e.pointerId)},stop=e=>{if(e)e.preventDefault();b.classList.remove('pressed');state.accelerating=false};b.addEventListener('pointerdown',go);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('pointerleave',stop);b.addEventListener('contextmenu',e=>e.preventDefault())});let touchStart=null;renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('selectstart',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart={x:e.clientX,y:e.clientY}},{passive:true});renderer.domElement.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;queue(Math.abs(dx)>Math.abs(dy)?dirs[dx>0?'right':'left']:dirs[dy>0?'down':'up'])},{passive:true});
 function togglePause(){if(!state.playing)return;state.paused=!state.paused;$('pause').textContent=state.paused?'▶':'Ⅱ';ui(state.paused?'Jogo pausado.':'Continue coletando!')}
 const tutorialSteps=[
  {icon:'🎮',title:'Movimente seu atleta',text:'Use as setas, WASD ou deslize o dedo pelo cenário para escolher uma direção.',visual:['▲','◀','▼','▶']},
  {icon:'💨',title:'Segure para acelerar',text:'Mantenha uma direção pressionada para ganhar velocidade. Ao soltar, o atleta desacelera com segurança.',visual:['TOQUE','SEGURE','CORRA']},
  {icon:'💧',title:'Colete e hidrate-se',text:'Cada garrafa vale 15 pontos. A cada 10 garrafas acontece uma pausa obrigatória de recuperação.',visual:['💧 +15','10×','🎉']},
  {icon:'🍫',title:'Complete as pausas',text:'Após 10 garrafas procure a barrinha, após 20 a fruta e após 30 o descanso. A água fica bloqueada até encontrar o item certo.',visual:['🍫','🍎','😴']},
  {icon:'⏱️',title:'Tempo e vidas',text:'Cada fase começa somente após seu toque. Você terá 2 minutos e 3 vidas; se o tempo zerar, a partida volta ao início.',visual:['02:00','♥ ♥ ♥']},
  {icon:'🟥',title:'Fuja do juiz',text:'O juiz de apito persegue você pelo circuito. Se alcançar seu atleta, mostrará cartão vermelho e você perderá uma vida.',visual:['👨‍⚖️','🟥','−1 ♥']},
  {icon:'⚡',title:'Complete as 3 fases',text:'Use escudo e turbo. Os itens de recuperação mudam de lugar em cada fase. Termine a fase 3 para entrar no ranking final!',visual:['1','2','3','🏆']}
 ];let tutorialIndex=0;
 function renderTutorial(){const step=tutorialSteps[tutorialIndex];$('tutorial-step-label').textContent=`PASSO ${tutorialIndex+1} DE ${tutorialSteps.length}`;$('tutorial-icon').textContent=step.icon;$('tutorial-title').textContent=step.title;$('tutorial-description').textContent=step.text;$('tutorial-visual').replaceChildren(...step.visual.map(value=>{const span=document.createElement('span');span.textContent=value;return span}));$('tutorial-dots').replaceChildren(...tutorialSteps.map((_,index)=>{const dot=document.createElement('span');if(index===tutorialIndex)dot.className='active';return dot}));$('next-tutorial').textContent=tutorialIndex===tutorialSteps.length-1?'Começar a jogar ✓':'Próximo →'}
 function openTutorial(){tutorialIndex=0;renderTutorial();$('tutorial').classList.add('visible')}
 function closeTutorial(){localStorage.setItem('be-game-tutorial-seen','yes');$('tutorial').classList.remove('visible')}
 $('next-tutorial').addEventListener('click',()=>{if(tutorialIndex<tutorialSteps.length-1){tutorialIndex++;renderTutorial()}else closeTutorial()});$('skip-tutorial').addEventListener('click',closeTutorial);$('open-tutorial').addEventListener('click',openTutorial);if(localStorage.getItem('be-game-tutorial-seen')!=='yes')setTimeout(openTutorial,350);
 async function toggleFullscreen(){await unlockAudio();try{if(document.documentElement.requestFullscreen){if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();return}document.body.classList.toggle('theater-mode');scrollTo(0,1);ui(document.body.classList.contains('theater-mode')?'Tela ampliada. No iPhone, use Compartilhar › Adicionar à Tela de Início para tela total.':'Tela normal restaurada.')}catch(error){document.body.classList.toggle('theater-mode');scrollTo(0,1);ui('No iPhone, use Compartilhar › Adicionar à Tela de Início para jogar em tela total.')}}
 async function rotateScreen(){const landscape=innerWidth>innerHeight;try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();await screen.orientation?.lock(landscape?'portrait':'landscape');ui(landscape?'Modo vertical ativado.':'Modo horizontal ativado.')}catch(error){ui('Gire o celular e desative o bloqueio de rotação, se necessário.')}}
 $('fullscreen').addEventListener('click',toggleFullscreen);$('rotate-screen').addEventListener('click',rotateScreen);$('next-level').addEventListener('click',nextLevel);$('start-level').addEventListener('click',async()=>{await unlockAudio();state.playing=true;state.paused=false;state.invincible=2;$('phase-ready').classList.remove('visible');ui(`Fase ${state.level} iniciada: o relógio está valendo!`)});$('play-again').addEventListener('click',()=>{$('game-finished').classList.remove('visible');maze=baseMaze.map(row=>[...row]);buildMaze(1);reset(true);$('overlay').classList.add('visible')});document.addEventListener('fullscreenchange',()=>{$('fullscreen').firstChild.textContent=document.fullscreenElement?'✕ ':'⛶ '});
 $('pause').onclick=togglePause;$('restart').onclick=()=>{reset(true);startRankedRun();state.playing=false;$('overlay').classList.add('visible')};$('start').onclick=async()=>{await unlockAudio();reset(true);startRankedRun();state.playing=true;state.paused=false;document.querySelector('.card h1').innerHTML='Corrida da<br><em>Hidratação</em>';document.querySelector('.card>p:not(.eyebrow)').textContent='Explore o labirinto 3D, colete água e energia e não deixe o juiz alcançar você.';$('start').textContent='Começar partida';$('overlay').classList.remove('visible')};document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.playing&&!state.paused)togglePause()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(lowPower?1:Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight)});reset(true);loop();
});
