window.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id), container=$('game-container');
 if(!window.THREE){$('message').textContent='Não foi possível carregar o motor 3D. Verifique sua conexão.';return}
 const scene=new THREE.Scene(); scene.background=new THREE.Color(0x06101f); scene.fog=new THREE.Fog(0x06101f,42,78);
 const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,150), renderer=new THREE.WebGLRenderer({antialias:true});
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;container.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0x9ddcff,0x06101f,1.25));const sun=new THREE.DirectionalLight(0xffffff,1.4);sun.position.set(-18,35,16);sun.castShadow=true;scene.add(sun);
 const maze=[[1,1,1,1,1,1,1,1,1,1,1,1,1],[1,0,0,0,1,0,0,0,1,0,0,0,1],[1,0,1,0,1,0,1,0,1,0,1,0,1],[1,0,1,0,0,0,1,0,0,0,1,0,1],[1,0,1,1,1,0,1,1,1,0,1,0,1],[1,0,0,0,0,0,0,0,1,0,0,0,1],[1,1,1,0,1,1,1,0,1,1,1,0,1],[1,0,0,0,1,0,0,0,0,0,0,0,1],[1,0,1,1,1,0,1,1,1,0,1,0,1],[1,0,0,0,0,0,0,0,1,0,0,0,1],[1,1,1,1,1,1,1,1,1,1,1,1,1]],CELL=4,rows=maze.length,cols=maze[0].length,ox=-(cols-1)*CELL/2,oz=-(rows-1)*CELL/2;
 const world=(x,y)=>new THREE.Vector3(ox+x*CELL,0,oz+y*CELL),open=(x,y)=>maze[y]?.[x]===0;
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(cols*CELL+12,rows*CELL+12),new THREE.MeshStandardMaterial({color:0x0b2335,roughness:.82}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
 const grid=new THREE.GridHelper(cols*CELL+12,cols+3,0x167c73,0x104055);grid.position.y=.02;scene.add(grid);
 const wallGeo=new THREE.BoxGeometry(CELL*.94,2.8,CELL*.94),wallMat=new THREE.MeshStandardMaterial({color:0x126390,roughness:.35,metalness:.25});
 maze.forEach((row,y)=>row.forEach((v,x)=>{if(v){const m=new THREE.Mesh(wallGeo,wallMat);m.position.copy(world(x,y));m.position.y=1.4;m.castShadow=m.receiveShadow=true;scene.add(m);const cap=new THREE.Mesh(new THREE.BoxGeometry(CELL*.82,.12,CELL*.82),new THREE.MeshBasicMaterial({color:0x21b9b1}));cap.position.set(m.position.x,2.86,m.position.z);scene.add(cap)}}));
 function athlete(color){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.SphereGeometry(.82,24,18),new THREE.MeshStandardMaterial({color,roughness:.35}));body.scale.set(1,1.1,1);body.castShadow=true;g.add(body);const visor=new THREE.Mesh(new THREE.BoxGeometry(1.05,.28,.35),new THREE.MeshStandardMaterial({color:0x07111f,metalness:.7}));visor.position.set(0,.2,.72);g.add(visor);[-.48,.48].forEach(x=>{const shoe=new THREE.Mesh(new THREE.BoxGeometry(.38,.25,.68),new THREE.MeshStandardMaterial({color:0xffffff}));shoe.position.set(x,-.77,.18);g.add(shoe)});g.position.y=1;scene.add(g);return g}
 const enemy=athlete(0xff4058);enemy.scale.set(1.12,1.12,1.12);let player=new THREE.Group();scene.add(player);
 const characterNames=['Futebol','Basquete','Vôlei','Tênis','Beisebol','Futebol Americano'];let characterCanvas=null;
 function removeMagenta(img){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const p=ctx.getImageData(0,0,c.width,c.height),d=p.data;for(let i=0;i<d.length;i+=4){const power=d[i]+d[i+2]-d[i+1]*1.45;if(d[i]>170&&d[i+2]>150&&power>160){d[i+3]=255-Math.max(0,Math.min(255,(power-160)*3));d[i]=Math.min(d[i],d[i+1]);d[i+2]=Math.min(d[i+2],d[i+1])}}ctx.putImageData(p,0,0);return c}
 function characterTexture(index){const col=index%3,row=Math.floor(index/3),cell=document.createElement('canvas');cell.width=characterCanvas.width/3;cell.height=characterCanvas.height/2;cell.getContext('2d').drawImage(characterCanvas,col*cell.width,row*cell.height,cell.width,cell.height,0,0,cell.width,cell.height);return cell}
 function selectCharacter(index){document.querySelectorAll('#characters button').forEach((b,i)=>b.classList.toggle('selected',i===index));$('character-name').textContent=characterNames[index];player.clear();const texture=new THREE.CanvasTexture(characterTexture(index));texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,alphaTest:.08}));sprite.scale.set(4.4,4.4,1);sprite.position.y=1.25;player.add(sprite)}
 function loadCharacters(){const img=new Image();img.src='img/personagens-3d-chroma.png';img.onload=()=>{requestAnimationFrame(()=>{characterCanvas=removeMagenta(img);const holder=$('characters');characterNames.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.title=name;b.setAttribute('aria-label',name);b.appendChild(characterTexture(i));b.onclick=()=>selectCharacter(i);holder.appendChild(b)});selectCharacter(0)})};img.onerror=()=>{$('character-name').textContent='Personagem padrão'}}loadCharacters();
 const itemGroup=new THREE.Group();scene.add(itemGroup);let itemCells=[];
 function makeItem(type,x,y){const g=new THREE.Group();if(type==='water'){const plastic=new THREE.MeshPhysicalMaterial({color:0x9be9ff,transparent:true,opacity:.78,roughness:.12,metalness:0,transmission:.12});const body=new THREE.Mesh(new THREE.CylinderGeometry(.32,.38,1.05,20),plastic);body.position.y=-.05;g.add(body);const shoulder=new THREE.Mesh(new THREE.CylinderGeometry(.20,.32,.25,20),plastic);shoulder.position.y=.58;g.add(shoulder);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.22,16),plastic);neck.position.y=.80;g.add(neck);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.205,.205,.16,16),new THREE.MeshStandardMaterial({color:0x176bd6,roughness:.45}));cap.position.y=.98;g.add(cap);const label=new THREE.Mesh(new THREE.CylinderGeometry(.325,.365,.34,20),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.55}));label.position.y=-.03;g.add(label);const stripe=new THREE.Mesh(new THREE.CylinderGeometry(.332,.372,.13,20),new THREE.MeshStandardMaterial({color:0x14bfe8}));stripe.position.y=-.03;g.add(stripe);g.scale.set(.9,.9,.9)}else{const wrapper=new THREE.Mesh(new THREE.BoxGeometry(1.15,.48,.35),new THREE.MeshStandardMaterial({color:0xffb52e,emissive:0x6b3500,roughness:.35}));wrapper.rotation.z=-.15;g.add(wrapper)}g.position.copy(world(x,y));g.position.y=.95;g.userData={type,x,y,value:type==='water'?15:25};itemGroup.add(g)}
 const state={score:0,level:1,lives:3,collected:0,water:0,total:0,playing:false,paused:false,player:{x:1,y:1},target:{x:1,y:1},enemy:{x:11,y:9},enemyTarget:{x:11,y:9},queued:null,heading:null,accelerating:false,speed:8.2,enemyTimer:0,invincible:0};
 function populate(){itemGroup.clear();itemCells=[];maze.forEach((row,y)=>row.forEach((v,x)=>{if(!v&&!(x===1&&y===1)&&!(x===11&&y===9)&&(x+y)%2===1)itemCells.push({x,y,type:(x*3+y)%4===0?'bar':'water'})}));itemCells.forEach(i=>makeItem(i.type,i.x,i.y));state.total=itemCells.length;state.collected=0}
 function place(){player.position.copy(world(state.player.x,state.player.y));player.position.y=1;enemy.position.copy(world(state.enemy.x,state.enemy.y));enemy.position.y=1}
 function ui(msg){$('score').textContent=state.score;$('level').textContent=state.level;$('lives').textContent='♥ '.repeat(state.lives).trim();$('items').textContent=`${state.collected}/${state.total}`;$('water-count').textContent=state.water;if(msg)$('message').textContent=msg}
 function reset(all=true){if(all){state.score=0;state.level=1;state.lives=3;state.water=0}state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.accelerating=false;state.speed=8.2;state.invincible=1.5;populate();place();ui('Segure uma direção para acelerar. O vilão já está procurando você!')}
 const dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
 function queue(d){state.queued=d;if(state.playing&&!state.paused)tryMove()}
 function tryMove(){if(player.position.distanceTo(world(state.target.x,state.target.y).setY(1))>.16)return;state.player={...state.target};let d=state.queued;if(d&&open(state.player.x+d.x,state.player.y+d.y)){state.heading=d}else{d=state.heading}if(d&&open(state.player.x+d.x,state.player.y+d.y))state.target={x:state.player.x+d.x,y:state.player.y+d.y};else state.heading=null}
 function nextEnemy(){const start=state.enemy,goal=state.player,q=[start],seen=new Set([`${start.x},${start.y}`]),prev=new Map();let found=null;while(q.length){const c=q.shift();if(c.x===goal.x&&c.y===goal.y){found=c;break}Object.values(dirs).forEach(d=>{const n={x:c.x+d.x,y:c.y+d.y},k=`${n.x},${n.y}`;if(open(n.x,n.y)&&!seen.has(k)){seen.add(k);prev.set(k,c);q.push(n)}})}if(!found)return;let step=found,parent=prev.get(`${step.x},${step.y}`);while(parent&&!(parent.x===start.x&&parent.y===start.y)){step=parent;parent=prev.get(`${step.x},${step.y}`)}state.enemyTarget={...step}}
 function hit(){if(state.invincible>0)return;const finalScore=state.score;state.playing=false;state.paused=false;reset(true);$('overlay').classList.add('visible');document.querySelector('.card h1').innerHTML='Você foi<br><em>capturado!</em>';document.querySelector('.card>p:not(.eyebrow)').textContent=`Você marcou ${finalScore} pontos. O jogo foi reiniciado: escolha seu atleta e tente novamente.`;$('start').textContent='Tentar novamente';$('pause').textContent='Ⅱ'}
 function complete(){state.playing=false;state.accelerating=false;state.score+=100;ui('Missão concluída! Bônus de 100 pontos.');$('result-level').textContent=state.level;$('result-score').textContent=state.score;$('result-water').textContent=state.water;$('mission-complete').classList.add('visible')}
 function nextLevel(){state.level++;state.player={x:1,y:1};state.target={...state.player};state.enemy={x:11,y:9};state.enemyTarget={...state.enemy};state.queued=null;state.heading=null;state.speed=8.2;populate();place();state.invincible=1.5;state.playing=true;$('mission-complete').classList.remove('visible');ui(`Fase ${state.level}! O vilão ficou mais rápido.`)}
 const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),t=performance.now()/1000,target=world(state.target.x,state.target.y).setY(1);if(state.playing&&!state.paused){state.invincible=Math.max(0,state.invincible-dt);const desiredSpeed=state.accelerating?14.5:8.2;state.speed+=Math.sign(desiredSpeed-state.speed)*Math.min(Math.abs(desiredSpeed-state.speed),dt*(state.accelerating?4.2:9));const step=state.speed*dt,distance=player.position.distanceTo(target);if(distance>step)player.position.add(target.clone().sub(player.position).normalize().multiplyScalar(step));else{player.position.copy(target);tryMove()}state.enemyTimer+=dt;if(enemy.position.distanceTo(world(state.enemyTarget.x,state.enemyTarget.y).setY(1))<.12){state.enemy={...state.enemyTarget};if(state.enemyTimer>.38-Math.min(.15,state.level*.018)){state.enemyTimer=0;nextEnemy()}}enemy.position.lerp(world(state.enemyTarget.x,state.enemyTarget.y).setY(1),Math.min(1,dt*(3+state.level*.13)));itemGroup.children.slice().forEach(i=>{i.rotation.y+=dt*1.7;i.position.y=.95+Math.sin(t*3+i.userData.x)*.12;if(player.position.distanceTo(i.position)<1.2){state.score+=i.userData.value;state.collected++;if(i.userData.type==='water')state.water++;itemGroup.remove(i);ui(i.userData.type==='water'?`+15 pontos · Garrafa ${state.water}`:'+25 pontos · Energia!');if(!itemGroup.children.length)complete()}});if(player.position.distanceTo(enemy.position)<1.45)hit()}camera.position.lerp(new THREE.Vector3(player.position.x,30,player.position.z+27),.06);camera.lookAt(player.position.x,0,player.position.z-2);renderer.render(scene,camera)}
 const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'},heldKeys=new Set();addEventListener('keydown',e=>{if(keyMap[e.key]){e.preventDefault();heldKeys.add(e.key);state.accelerating=true;queue(dirs[keyMap[e.key]])}if(e.code==='Space'){e.preventDefault();togglePause()}});addEventListener('keyup',e=>{if(keyMap[e.key]){heldKeys.delete(e.key);state.accelerating=heldKeys.size>0}});addEventListener('blur',()=>{heldKeys.clear();state.accelerating=false});document.querySelectorAll('[data-dir]').forEach(b=>{const go=e=>{e.preventDefault();b.classList.add('pressed');state.accelerating=true;queue(dirs[b.dataset.dir]);if(b.setPointerCapture)b.setPointerCapture(e.pointerId)},stop=()=>{b.classList.remove('pressed');state.accelerating=false};b.addEventListener('pointerdown',go);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('pointerleave',stop)});let touchStart=null;renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart={x:e.clientX,y:e.clientY}},{passive:true});renderer.domElement.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24)return;queue(Math.abs(dx)>Math.abs(dy)?dirs[dx>0?'right':'left']:dirs[dy>0?'down':'up'])},{passive:true});
 function togglePause(){if(!state.playing)return;state.paused=!state.paused;$('pause').textContent=state.paused?'▶':'Ⅱ';ui(state.paused?'Jogo pausado.':'Continue coletando!')}
 async function toggleFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()}catch(error){ui('Use a opção de tela cheia do navegador.')}}
 async function rotateScreen(){const landscape=innerWidth>innerHeight;try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();await screen.orientation?.lock(landscape?'portrait':'landscape');ui(landscape?'Modo vertical ativado.':'Modo horizontal ativado.')}catch(error){ui('Gire o celular e desative o bloqueio de rotação, se necessário.')}}
 $('fullscreen').addEventListener('click',toggleFullscreen);$('rotate-screen').addEventListener('click',rotateScreen);$('next-level').addEventListener('click',nextLevel);document.addEventListener('fullscreenchange',()=>{$('fullscreen').firstChild.textContent=document.fullscreenElement?'✕ ':'⛶ '});
 $('pause').onclick=togglePause;$('restart').onclick=()=>reset(true);$('start').onclick=()=>{reset(true);state.playing=true;state.paused=false;document.querySelector('.card h1').innerHTML='Corrida da<br><em>Hidratação</em>';document.querySelector('.card>p:not(.eyebrow)').textContent='Explore o labirinto 3D, colete água e energia e não deixe o marcador vermelho alcançar você.';$('start').textContent='Começar partida';$('overlay').classList.remove('visible')};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});reset(true);loop();
});
