name = "bemesportivo"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-30"

[[env.production.kv_namespaces]]
binding = "BE_DATA"
id = "c14e9a5a746c4f459063ce7d7711efeb"

[[env.production.services]]
binding = "CONTACT_EMAIL_SERVICE"
service = "bemesportivo-contact-email"

[env.production.vars]
CONTACT_FROM_EMAIL = "contato@bemesportivo.com"
