name = "bemesportivo"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-30"

[[env.production.kv_namespaces]]
binding = "BE_DATA"
id = "c14e9a5a746c4f459063ce7d7711efeb"

[[env.production.send_email]]
name = "CONTACT_EMAIL"
destination_address = "bemesportivo@yahoo.com"
allowed_sender_addresses = ["contato@bemesportivo.com"]

[env.production.vars]
CONTACT_FROM_EMAIL = "contato@bemesportivo.com"
