const { test, expect } = require('@playwright/test');
test.use({ serviceWorkers: 'block' });
test('home oferece teclado, busca direta e preferencia reversivel', async ({ page }) => {
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:3100' ? route.continue() : route.abort());
  await page.addInitScript(() => localStorage.setItem('bemEsportivoPrivacyConsentV1', JSON.stringify({ version: 2, necessary: true, measurement: false, advertising: false })));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.keyboard.press('Tab');
  await expect(page.locator('.home-skip-link')).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.locator('#main-content')).toBeFocused();
  await page.locator('#be-ecosystem-search-input').fill('Quero começar a correr');
  await page.locator('#be-ecosystem-search-form').getByRole('button', { name: 'Encontrar' }).click();
  await expect(page.locator('#be-search-result-title')).toBeFocused();
  await expect(page.locator('#be-ecosystem-search-results')).toContainText('Minha primeira corrida');
  await page.locator('#home-interest').selectOption('futebol');
  await page.reload();
  await expect(page.locator('#home-interest')).toHaveValue('futebol');
  await page.locator('#home-interest').selectOption('corrida');
  await expect(page.locator('#be-ecosystem-search-results')).toContainText('Minha primeira corrida');
  await page.locator('#home-interest').selectOption('');
  expect(await page.evaluate(() => localStorage.getItem('bemEsportivoSportPreferenceV1'))).toBeNull();
  await expect(page.locator('#be-search-result-title')).toHaveText('Para começar a explorar');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto('/');
  await page.screenshot({ path: '.local-reference/home-mobile-improved.png', fullPage: false });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: '.local-reference/home-desktop-improved.png', fullPage: false });
});
